import JSZip from 'jszip';
import { saveAs } from 'file-saver';

/**
 * Packages generated artifacts into a runnable full-stack codebase zip
 */
export async function exportBlueprintAsZip(artifacts) {
  if (!artifacts) return;

  const zip = new JSZip();
  const title = artifacts.prd?.projectTitle || 'DevSprint_Project';
  const cleanFolderName = title.replace(/[^a-zA-Z0-9_-]/g, '_').toLowerCase();

  // Root folder in zip
  const root = zip.folder(cleanFolderName);

  // 1. README.md
  let readmeContent = `# ${title}\n\n`;
  readmeContent += `> Generated by **DevSprint Workspace** (Autonomous Multi-Agent AI Engine)\n\n`;
  readmeContent += `## Overview\n${artifacts.prd?.summary || 'No summary available.'}\n\n`;
  
  if (artifacts.prd?.coreFeatures) {
    readmeContent += `## Core Features\n`;
    artifacts.prd.coreFeatures.forEach(feat => {
      readmeContent += `- **${feat.featureName}** [${feat.priority || 'High'}]: ${feat.description}\n`;
    });
    readmeContent += `\n`;
  }

  if (artifacts.architecture?.apiRoutes) {
    readmeContent += `## API Endpoints\n`;
    artifacts.architecture.apiRoutes.forEach(route => {
      readmeContent += `- \`${route.method} ${route.path}\` - ${route.description}\n`;
    });
    readmeContent += `\n`;
  }

  root.file('README.md', readmeContent);

  // 2. Server Folder (`server/`)
  const serverFolder = root.folder('server');
  
  // server/package.json
  const serverPkg = {
    name: `${cleanFolderName}-server`,
    version: '1.0.0',
    type: 'module',
    main: 'server.js',
    scripts: {
      start: 'node server.js',
      dev: 'nodemon server.js'
    },
    dependencies: {
      express: '^4.19.2',
      mongoose: '^8.5.1',
      cors: '^2.8.5',
      dotenv: '^16.4.5'
    }
  };
  serverFolder.file('package.json', JSON.stringify(serverPkg, null, 2));

  // server/models/
  const modelsFolder = serverFolder.folder('models');
  if (artifacts.database?.schemas) {
    artifacts.database.schemas.forEach(schema => {
      modelsFolder.file(schema.fileName || 'Model.js', schema.code);
    });
  } else {
    modelsFolder.file('User.js', '// Mongoose User Schema Placeholder');
  }

  // 3. Client Folder (`client/`)
  const clientFolder = root.folder('client');
  const componentsFolder = clientFolder.folder('src').folder('components');

  if (artifacts.frontend?.componentSuite) {
    artifacts.frontend.componentSuite.forEach(comp => {
      componentsFolder.file(comp.componentName || 'Component.jsx', comp.code);
    });
  } else {
    componentsFolder.file('App.jsx', '// React Component Suite Placeholder');
  }

  // Generate ZIP file & trigger browser download
  const blob = await zip.generateAsync({ type: 'blob' });
  saveAs(blob, `${cleanFolderName}_codebase.zip`);
}
